import type { Metadata } from "next";

import "./globals.css";

import localFont from 'next/font/local';


const OpenSans = localFont({
  src: '../public/fonts/Inter-VariableFont_opsz,wght.ttf', 
  display: 'swap',
  variable: '--font-openSans',
});

export const metadata: Metadata = {
  title: "ELdokan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${OpenSans.variable} ${OpenSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col  pt-1">{children}</body>
    </html>
  );
}
